<?php

use App\Http\Controllers\AttendanceController;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\CertificateController;
use App\Http\Controllers\CourseController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\FeedbackController;
use App\Http\Controllers\SettingsController;
use App\Http\Controllers\TeacherController;
use App\Http\Controllers\TrainerController;
use App\Http\Controllers\UnifiedAuthController;
use App\Models\AuditLog;
use App\Models\Certificate;
use App\Models\Course;
use App\Models\FeedbackForm;
use App\Models\Trainer;
use Illuminate\Support\Facades\Route;

Route::get('/', fn () => redirect()->route('login'));

/*
|--------------------------------------------------------------------------
| Laravel module routes
|--------------------------------------------------------------------------
| The .php paths are intentionally kept as compatibility URLs so the
| existing TrainHub V4 links and redirects continue to work during the
| migration. Clean aliases are provided below.
*/
Route::match(['GET', 'POST'], '/login.php', [UnifiedAuthController::class, 'login'])->name('login');
Route::match(['GET', 'POST'], '/choose-role.php', [UnifiedAuthController::class, 'roles'])->name('auth.roles');
Route::match(['GET', 'POST'], '/choose-system.php', [UnifiedAuthController::class, 'systems'])->name('auth.systems');
Route::match(['GET', 'POST'], '/forgot_password.php', [AuthController::class, 'forgotPassword'])->name('password.forgot');
Route::match(['GET', 'POST'], '/logout.php', [UnifiedAuthController::class, 'logout'])->name('logout');

Route::match(['GET', 'POST'], '/dashboard.php', [DashboardController::class, 'index'])->name('dashboard');
Route::match(['GET', 'POST'], '/teacher.php', [TeacherController::class, 'index'])->name('teacher.index');
Route::match(['GET', 'POST'], '/course.php', [CourseController::class, 'index'])->name('course.index');
Route::match(['GET', 'POST'], '/trainer.php', [TrainerController::class, 'index'])->name('trainer.index');
Route::match(['GET', 'POST'], '/feedback.php', [FeedbackController::class, 'index'])->name('feedback.index');
Route::match(['GET', 'POST'], '/certificate.php', [CertificateController::class, 'index'])->name('certificate.index');
Route::match(['GET', 'POST'], '/settings.php', [SettingsController::class, 'index'])->name('settings.index');
Route::match(['GET', 'POST'], '/attendance.php', [AttendanceController::class, 'index'])->name('attendance');

// Optional clean Laravel URLs.
Route::redirect('/dashboard', '/dashboard.php');
Route::redirect('/teachers', '/teacher.php');
Route::redirect('/trainings', '/course.php');
Route::redirect('/trainers', '/trainer.php');
Route::redirect('/feedback', '/feedback.php');
Route::redirect('/certificates', '/certificate.php');
Route::redirect('/settings', '/settings.php');
Route::redirect('/attendance', '/attendance.php');

// Files generated by legacy-compatible services are written under app/Legacy
// because the original V4 filesystem logic uses __DIR__. Public static files
// are served directly first; these routes serve newly generated files.
Route::get('/uploads/{path}', function (string $path) {
    $safe = str_replace(['..', '\\'], '', $path);
    $file = app_path('Legacy/uploads/'.$safe);
    abort_unless(is_file($file), 404);
    return response()->file($file);
})->where('path', '.*');

Route::get('/generated/{path}', function (string $path) {
    $safe = str_replace(['..', '\\'], '', $path);
    $file = app_path('Legacy/generated/'.$safe);
    abort_unless(is_file($file), 404);
    return response()->file($file);
})->where('path', '.*');

// Local-only migration diagnostic: confirms Eloquent can read fyp2.0.
if (app()->environment('local')) {
    Route::get('/laravel-status', function () {
        return response()->json([
            'application' => 'TrainHub Al Amin',
            'framework' => app()->version(),
            'database' => config('database.connections.mysql.database'),
            'counts' => [
                'courses' => Course::query()->count(),
                'trainers' => Trainer::query()->count(),
                'feedback_forms' => FeedbackForm::query()->count(),
                'certificates' => Certificate::query()->count(),
                'audit_logs' => AuditLog::query()->count(),
            ],
        ]);
    })->name('laravel.status');
}
